### ISSUE TITLE
Does not expand replies anymore.

### ISSUE THREAD

**Issue by martinramirezz** [hckr/fb-post-screenshot#4] opened 2019-03-04 04:40 UTC
Hi, I'm completely new to GitHub so excuse me if I'm not doing this the right way. You're allowed to edit my post to make it suitable.

I just needed a way to contact you because I'm a fan of the add-on called 'Facebook Post Screenshot' by hckr and I needed to inform you that it's not working correctly as it used to do.

I don't know if something was changed on Facebook to cause this but when I want to take a screenshot of a Facebook post (at least from within a group), the replies to the post are not fully expanded anymore and I'm quite sure they did.

It just downloads a screenshot with the current state of the post without expanding all the replies. I've just tested it with a 110-replies post and then with others of different number of replies and it's the same for all of them.

Reading through the comments on the Add-on site I noticed I might not be the only one experiencing this.

My first thought was that it had something to do with the Firefox version I was using (Firefox 56.0), maybe the newest versions might have caused this. But when I downgraded to Firefox 54.0 (oldest version accepted by this add-on) and I tried to repeat the process, the result was exactly the same than with Firefox 56.0: Only 1 screenshot generated instead of multiple ones, without replies expanded.

So here I am trying to inform you this and I'd like to ask you if you could update or fix this beautiful and useful add-on to make it work again. I'll be waiting for an update to finally take a screenshot of the post I need because currently there's no other way to do it as far as I know and the default Firefox Screenshots add-on is never able to detect the area of a Facebook post.

Well, that's all so time to say good-bye for me and thank you for all your effort because you're the only one to create an add-on such as this.

Bye.

**Comment by hckr** [comment] 2019-03-05 11:51
Thank you for filing the issue, I'll try to fix this as soon as possible.

**Comment by hckr** [comment] 2019-03-07 22:27
I've uploaded a fixed version to the Firefox add-ons website and it should be available to you right now.
Additionally, option to make a screenshot should now appear in all posts' menus – also a theater view (but I, of course, could've missed something  :stuck_out_tongue_closed_eyes:).

I'm closing the issue, but feel free to add something if you need.

**Comment by hckr** [comment] 2019-03-08 11:42
I actually found some more isssues, will fix them in the evening.

**Comment by martinramirezz** [comment] 2019-03-10 06:30
Hi hckr! First of all, thanks a million for fixing the issue! I can't believe I could finally save the post I needed. I'm so happy and grateful for that. I downloaded it with version 1.6.0 and it worked like a charm.

Just for info, I just tested the last update 1.6.3 to try the new changes (I liked the new cosmetic changes btw) but I have to tell you that right after the screenshooting process finishes, the window which is supposed to ask me where to save the screenshot pops up but it disappears inmediately after appearing. Since I can't see that window, I can't save any of the screenshots. I suppose you're still making changes though so I didn't open a new thread just for this, but I can do it if that's your wish.

Important Note:
I have Firefox always configured so that I can decide the destination folder of every downloaded file instead of 'Automatically save in Downloads folder'. I assumed this had some influence in the issue so I changed my Firefox settings to 'Automatically save in Downloads folder'. When I did this, the screenshots were saved correctly (to the default Downloads folder). So I hope this gives you a clue about what's causing the little issue when Firefox is set to 'always ask where to download the files.

With 1.6.0, I could download all the screenshots without changing my Firefox settings.

Just a suggestion:
Would it be possible to save the screenshots in PNG by default for better quality?

**Comment by hckr** [comment] 2019-03-10 17:45
>Would it be possible to save the screenshots in PNG by default for better quality?

Yes, it should be possible. I guess I'll just add the option in settings for this.

>Since I can't see that window, I can't save any of the screenshots.

Yes, I've changed it in the newest version to use the [`downloads`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download) API. I thought it would work better, not worse than previously... (Someone else told me he had issues with saving multiple parts of the screenshot)

Thanks for informing me about all those issues, thanks to this I can work on them. I cannot promise I'll fix all those at once, but I'll be working on it.

**Comment by hckr** [comment] 2019-03-11 01:24
I've updated the extension on add-ons website. It should work correctly with this other option for saving files that you prefer.

The root cause of the problem is pretty weird – when Firefox receives a command to download files from so-called [background script](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#Communicating_with_background_scripts), the popup for path selection appears to be opened with the window which has focus at the moment, which in this example was the popup which was going to disappear in 3 seconds, taking the path selection window with itself. :open_mouth:

**Closed as completed** 2019-03-12 13:03 UTC
Labels: bug, enhancement
